/*
 * Copyright (C) 2017 LittleRover
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.auroraengine.debug;

import java.util.logging.Logger;

/**
 * A generic exception object used for exceptions generated by the code in this
 * project.
 *
 * @author LittleRover
 */
public class AuroraException extends Exception {
	private static final Logger LOG = Logger.getLogger(AuroraException.class
					.getName());
	private static final long serialVersionUID = 1L;

	/**
	 * Creates a new exception with the specified message.
	 *
	 * @param msg The message
	 */
	public AuroraException(String msg) {
		super(msg);
	}

	/**
	 * Creates a new exception with the specified message caused by the specified
	 * throwable.
	 *
	 * @param msg   The message
	 * @param cause The cause of this exception.
	 */
	public AuroraException(String msg, Throwable cause) {
		super(msg, cause);
	}

	/**
	 * Creates a new exception caused by the specified throwable.
	 *
	 * @param cause The cause of this exception.
	 */
	public AuroraException(Throwable cause) {
		super(cause);
	}
}
